name: "dbt_google_analytics"
version: "1.0.0"
config-version: 2

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: target
log-path: logs
packages-install-path: dbt_packages

models:
  dbt_google_analytics:
    +persist_docs:
      relation: true
      columns: true
